### ISSUE TITLE
Android onActivityResult 没有判断requestCode 导致处理了其他库的返回信息而崩溃

### ISSUE THREAD

**Issue by fwlong** [gitSirzh/react-native-contact-form#3]
同时使用了 imagepicker 和 contact-form ； 选择图片返回后，uri 被contact-form拦截处理；因为数据库字段不一直导致崩溃

**Comment by gitSirzh** [comment]
> 同时使用了imagepicker和contact-form；选择图片返回后，uri被contact-form拦截处理；因为数据库中断不一直导致崩溃

你好，可以发下报错信息和使用react-native-imagepicker库、react-native版本吗

**Comment by gitSirzh** [comment]
你好，requestCode 判断已经修复，后续有什么问题欢迎提 issues

**Comment by gitSirzh** [comment]
> > 同时使用了imagepicker和contact-form；选择图片返回后，uri被contact-form拦截处理；因为数据库中断不一直导致崩溃
> 
> 你好，可以发下报错信息和使用react-native-imagepicker库、react-native版本吗

请更新组件库到最新版 v1.2.4
